Function dictionary revision
tfcp68/yantrix pull request #124
Opened 2024-09-01 15:18 UTC by denis-perevertov

- сделал из `FunctionDictionary` синглтон
- создал отдельный интерфейс для всех классов , которые могут что-то делать с функциями автоматов - `IAutomataFunctionRegistry`
- внутри сгенерированного автомата добавил поле `functionRegistry` типа `IAutomataFunctionRegistry` , в котором изначально хранится ссылка на общий словарь функций в слайсе; есть дополнительные методы `getFunctionRegistry` и `setFunctionRegistry` для изменения словаря для этого автомата
- функция для получения нового контекста теперь имеет вид не `(prevContext, payload) => {...}`, а `{prevContext, payload, functionRegistry} => {...}` , внутри каждого автомата дополнительно заряжается именно тот словарь , который им сейчас используется
- в конструктор автомата не добавлял словарь , и в function dictionary не учитывал возможность создавать по 1 словарю на слайс (сейчас создается 1 в целом) , но это легко поменять

2024-09-03 19:47 UTC, octaharon requested changes

2024-09-03 19:47 UTC, octaharon commented on packages/automata/src/FunctionDictionary.ts
> +/**
я думаю что буквально синглтон как паттерн это оверкилл. в нашем случае надо чтобы этот класс был один на сгенерированный бандл, но физически в проекте почему бы мне не создать их несколько для своих нужд? Кажется это перебор

2024-09-03 19:47 UTC, octaharon commented on packages/automata/src/FunctionDictionary.ts
> +	registerMultiple(
лучше расширить оригинальный метод тогда до списков. overwrite не нужен

2024-09-03 19:47 UTC, octaharon commented on packages/automata/src/types/interfaces.ts
> +	register(functionKey: string, callback: TAutomataFunction): TAutomataFunction;
а registerMultiple тут нет :) надо один интерфейс короче расширить так чтоб можно было словарь туда передавать

2024-09-03 19:47 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript.ts
> +			setFunctionRegistry(registry) {
а может лучше в init это вынести?

2024-09-03 19:47 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript.ts
> +				this.functionRegistry = registry;
тут ошибка, оно же `#functionRegistry`

2024-09-03 19:47 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript.ts
>  		return `export class ${className} extends GenericAutomata {
че-т такого размера портянка... может ее в отдельный файл как темплейт, и плейсхолдеры для замены?

2024-09-13 09:07 UTC, denis-perevertov commented on packages/automata/src/FunctionDictionary.ts
> +/**
убрал синглтон

2024-09-13 09:09 UTC, denis-perevertov commented on packages/codegen/src/core/modules/JavaScript.ts
> +		);
портянка стала не намного меньше размером

2024-09-13 13:20 UTC, merged