Fix selectors slice redux + eslint
tfcp68/yantrix pull request #132
Opened 2024-09-12 12:56 UTC by Nekitech

- [ ] увеличил max-len в eslint с 80 до 120
- [ ] поправил вывод селекторов из контекста

2024-09-12 21:33 UTC, obl1v1onZzz commented on packages/redux/src/index.ts
> +const { actions, name, reducer, selectors } = createFSMSlice({
Здесь явно не должно этого быть, давай удалим

2024-09-13 07:54 UTC, obl1v1onZzz approved these changes

2024-09-13 13:39 UTC, octaharon commented on packages/redux/src/slice/slice.ts
> +	let selectorsSlice = selectors || {
Object.assign({state:...,context:...}, selectors)

2024-09-13 14:00 UTC, octaharon commented on packages/redux/src/slice/slice.ts
> +	TCreateFSMSliceOptions,
fsm<AutomataType> должен extends IAutomata

2024-09-13 14:01 UTC, octaharon commented on packages/redux/src/slice/slice.ts
> +				return newState;
поправить тайпинг contextToRedux, он возвращает StateType, на 50 стркое операция не должна пройти проверку типов

2024-09-13 14:09 UTC, octaharon requested changes
поправить типизацию contextToRedux

2024-09-23 05:30 UTC, octaharon requested changes

2024-09-23 05:30 UTC, octaharon commented on examples/01-traffic-light/src/redux/store.ts
> +		redColorOn: [TLA.getState('Red'), TLA.getState('RedYellow')].includes(context.state),
форматните как-нить по-человечьи, пожалуйста)
типа
```
redColorOn: [
  TLA.getState('Red'),
  TLA.getState('RedYellow')
].includes(context.state)
  ```

2024-09-23 05:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript.ts
> +		this.dictionaries.push();
это че такое)

2024-09-23 05:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript.ts
> +			this.imports['@yantrix/functions'].push(FunctionName);
константу бы в константу, мало ли модуль поменяет адресацию

2024-09-23 05:30 UTC, octaharon commented on examples/01-traffic-light/package.json
>  		"@radix-ui/react-slot": "^1.1.0",
эта штука анимации добавляет? может выпилим? чем меньше зависимостей в экзампле тем очевиднее влияние нашей либы

2024-09-23 09:39 UTC, obl1v1onZzz commented on examples/01-traffic-light/package.json
>  		"@radix-ui/react-slot": "^1.1.0",
@octaharon 
Нет, это для своего UI кита.
Имхо для двух кнопок и светофора слишком много зависимостей,  предлагаю вообще все выпилить и оставить только react, redux, yantrix, бандл сайз так же станет меньше, что для доки мне кажется важно

2024-09-23 20:42 UTC, Nekitech commented on packages/codegen/src/core/modules/JavaScript.ts
> +		this.dictionaries.push();
Это осталось после мерджа ветки function-packages (https://github.com/tfcp68/yantrix/pull/137), там это уже убрано (https://github.com/tfcp68/yantrix/blob/functions-package/packages/codegen/src/core/modules/JavaScript.ts)

2024-09-23 20:52 UTC, Nekitech commented on examples/01-traffic-light/src/redux/store.ts
> +		redColorOn: [TLA.getState('Red'), TLA.getState('RedYellow')].includes(context.state),
поправил

2024-09-27 13:01 UTC, octaharon commented on examples/01-traffic-light/package.json
>  		"@radix-ui/react-slot": "^1.1.0",
> @octaharon Нет, это для своего UI кита. Имхо для двух кнопок и светофора слишком много зависимостей, предлагаю вообще все выпилить и оставить только react, redux, yantrix, бандл сайз так же станет меньше, что для доки мне кажется важно

тулинг можно оставить в dev dependencies, а остальное согласен - лучше минимизировать

2024-09-27 14:20 UTC, merged