Forks in codegen
tfcp68/yantrix pull request #135
Opened 2024-09-13 12:52 UTC by denis-perevertov

-- work in progress --

2024-09-27 13:51 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript.ts
> +					const isFunction = (str: string) => str.match(/^[a-z]+\([\w\s$#,()]+\)$/i);
плохая идея, проверять синтаксис отдельно от грамматики не стоит. надо использовать yantrix-parser

2024-09-27 14:26 UTC, obl1v1onZzz commented on packages/codegen/src/core/modules/JavaScript.ts
> +					const isFunction = (str: string) => str.match(/^[a-z]+\([\w\s$#,()]+\)$/i);
yantrix parser отдает тип выражения. В yantrix-parser typeguard заведи нужный тебе
![image](https://github.com/user-attachments/assets/451da0c0-b0fd-4eda-9b4a-5febf78804f7)

2024-10-04 13:54 UTC, octaharon requested changes
move forks parsing to mermaid-parser
generalize state name validation

2024-10-11 14:03 UTC, octaharon approved these changes

2024-10-14 14:15 UTC, merged