Events functionality in generated automatas
tfcp68/yantrix pull request #150
Opened 2024-10-22 10:48 UTC by denis-perevertov

2024-10-26 09:30 UTC, octaharon requested changes
изменения CLI вынести в отдельную ветку и PR!

2024-10-26 09:30 UTC, octaharon commented on packages/automata/src/Automata.ts
> +				if (eventDictionary == null) {
не должно быьт зависимости

2024-10-26 09:30 UTC, octaharon commented on packages/automata/src/types/index.ts
> +	eventDictionary?: IEventDictionary<EventType, Record<EventType, any>>;
тоже лишнее

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/events/serializer.ts
> +	return `GlobalEventDictionary.addEvents({ keys: Object.keys(eventDictionary).filter(e => GlobalEventDictionary.getEventValues({ keys: [e] })[0] == null) });`;
перенести в билд-тайм

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/events/serializer.ts
> +		const emittedEvents = state.notes?.emit;
- вынести генеративные шаблоны в самостоятельные переменные или функции
- минимизировать вайтспейс и переносы строк в сгенерированном коде
- ограничить длину строк, больше переносов

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/events/serializer.ts
> +	if (lines.length > 0) lines.unshift('// add event emitters');
вынести все промежуточные вычисления, независящие от языка, из языкового модуля
- mermaid-parser
- codegen/core

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/events/serializer.ts
> +	for (const state of props.diagram.states) {
много кода не зависящего от JS, можно вынести в отдельные методы core

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/events/serializer.ts
> +                    this.eventBus.subscribe(${eventId}, ({ event, meta }) => {
данный код должен быть в коде модуля адаптера 
или
в общем файле на весь сгенерированный бандл с eventbus и eventdictionary

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/events/serializer.ts
> +	if (result.length > 0) result.unshift('// add event listeners');
убрать

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/forks/serializer.ts
> +	for (const action in possibleActions) {
вынести логику отдельно в core, для сгенерированного кода использовать map

2024-10-26 09:30 UTC, octaharon commented on packages/codegen/src/core/modules/JavaScript/JavaScriptCompiler/forks/serializer.ts
> +function processStateActions(props: {
все вспомогательные функции прокомментировать, хотя бы что берет что отдает

2024-10-31 19:19 UTC, obl1v1onZzz commented on packages/codegen/src/core/modules/JavaScript/codegen.ts
> +					stateDictionary: this.stateDictionary,
Может собрать все поля класса в 1 объект, и пихать его везде?
И пусть сериалайзеры, берут то что им нужно?

2024-11-22 13:59 UTC, merged