Types codegen ts
tfcp68/yantrix pull request #66
Opened 2024-05-25 17:59 UTC by Volshebnik09

2024-05-26 08:29 UTC, octaharon commented on packages/codegen/src/core/modules/TypeScript.ts
> +	public getUtils() {
вынести в сгенерированный класс, убрать из интерфейса, и убрать внутренние зависимости

2024-05-26 08:34 UTC, octaharon commented on packages/codegen/src/core/Codegen.ts
> +import { fmt } from '../utils/utils.js';
форматирование вынести в отдельный компонент

2024-05-28 15:46 UTC, octaharon requested changes

2024-06-02 15:10 UTC, denis-perevertov commented on packages/codegen/src/core/Codegen.ts
> +const formatOutputByLanguage = {
мне кажется , таких словарей здесь не должно быть - нет возможности в интерфейс ICodegen добавить методы по типу getFullOutput() / format() , чтоб внутри каждого модуля прописывать реализацию этих вещей ?

2024-06-02 15:14 UTC, obl1v1onZzz commented on packages/codegen/src/types/common.ts
> +	 *            действие1: состояние2
Экспортируемый интерфейс = eng comments
А вообще везде лучше english

2024-06-02 16:19 UTC, octaharon commented on packages/codegen/src/core/Codegen.ts
> +const formatOutputByLanguage = {
удалить, больше не нужно

2024-06-09 08:28 UTC, merged