Test fixtures rework
tfcp68/yantrix pull request #70
Opened 2024-05-27 09:32 UTC by denis-perevertov

в пакете mermaid-parser исправил dev dependency "@yantrix/utils" с "*" на "workspace:^" , в проект можно добавлять новые либы без ошибок

в yantrix-parser:
 - добавил библиотеку immutableJS
 - папки fixtures и utils вынес из тестовой папки
 - во всех тестовых файлов поменял кейсы , чтоб они работали с рандомными именами/значениями (за несколькими исключениями)
 - в fixtures фикстуры создаются через функции
 - функции разбиты на несколько уровней , обновление фикстур происходит с использованием immutableJS

2024-05-28 15:37 UTC, octaharon commented on packages/yantrix-parser/src/utils/utils.ts
> +export const randomInteger = (min: number = 1, max: number = 100): number => Math.floor(Math.random() * 20000) - 10000;
мне кажется, подобные функции уже есть в тестах `Automata`. Мб их тогда вынести в `@yantrix/utils` в отдельный файл fixtures?

2024-05-28 15:39 UTC, octaharon commented on packages/yantrix-parser/src/fixtures/expressions.ts
> +	Map(primitives.string)
ну конкретно тут immutable как будто только усложняет, не? Можно было бы просто `Object.assign({},...) сделать?

2024-05-28 15:41 UTC, octaharon commented on packages/yantrix-parser/src/fixtures/expressions.ts
> +export const expressions: Record<TKeysPrimitive, TRecordExpression> = {
а если так, может одной функцией можно обойтись? ведь каждый из этих операторов по сути обходит весь объект итератором

2024-05-29 10:57 UTC, denis-perevertov commented on packages/yantrix-parser/src/utils/utils.ts
> +export const randomInteger = (min: number = 1, max: number = 100): number => Math.floor(Math.random() * 20000) - 10000;
Ну в принципе, можно кинуть `randomString` / `randomInteger` / `randomDecimal `в `@yantrix/utils`  , сделаю

2024-05-29 11:26 UTC, denis-perevertov commented on packages/yantrix-parser/src/fixtures/expressions.ts
> +export const expressions: Record<TKeysPrimitive, TRecordExpression> = {
типа такого ?
`export const expressions = <Record<TKeysPrimitive, TRecordExpression>> Object.fromEntries(
	Object.entries(primitives).map(
		([k, v]) => [k, getExpression(v)]
	)
)`

2024-05-29 11:27 UTC, denis-perevertov commented on packages/yantrix-parser/src/fixtures/expressions.ts
> +export const expressionProperties = {
не совсем понял - оставить только expressionProperties словарь ? надо там еще крутиться, смотреть чтоб типизация не сломалась) для тестовых фикстур наверное это не сильно важно, но все же

2024-06-02 15:05 UTC, obl1v1onZzz commented on packages/yantrix-parser/src/__test__/baseDeclaration.test.ts
>  	});
Как будто все можно вынести в словарь где ключ входная строка, значение expressionProperties

2024-06-02 15:05 UTC, obl1v1onZzz commented on packages/yantrix-parser/src/__test__/baseDeclaration.test.ts
> +			`#{${arg} == ${value}}`,
Мне кажется лучше не мешать  валидные и не валидные кейсы
Как минимум я думаю все не валидные кейсы вынести в одно место, и гонять их

2024-06-02 15:05 UTC, obl1v1onZzz commented on packages/yantrix-parser/src/__test__/functionDeclaration.test.ts
> +		});
Вкусовщина, но, как я понимаю тоже самое можно сделать, как было раньше ```test.each```

Имхо выглядит лучше

2024-06-02 15:07 UTC, obl1v1onZzz commented on packages/yantrix-parser/src/__test__/keyItem.test.ts
> -			assert.deepOwnInclude(output, res);
test.each

2024-06-02 15:53 UTC, octaharon commented on packages/yantrix-parser/src/__test__/baseDeclaration.test.ts
> +			`#{${arg} == ${value}}`,
корректные и некорректные надо разделить на разные describe, объединить со словарем в глобальном скопе

2024-06-02 16:15 UTC, octaharon requested changes

2024-06-02 16:15 UTC, octaharon commented on packages/yantrix-parser/src/__test__/baseDeclaration.test.ts
> +		const [arg, stringVal, intVal, decimalVal, funcName, propName] = [
переписать на словарь и вынести на уровень модуля

2024-06-02 16:15 UTC, octaharon commented on packages/yantrix-parser/src/__test__/baseDeclaration.test.ts
> +				`#{arg=[${randomInteger}, ${randomInteger}, ${randomInteger}]}`,
сделать генерацию N=1000 сэмплов произвольной длины 1<M<12 произвольных типов на основе словаря фикстур, выходной тип - tuple

2024-06-02 16:15 UTC, octaharon commented on packages/yantrix-parser/src/__test__/functionDeclaration.test.ts
> +			`#{${propertyName1}=${funcName1}(${integerProperty})}`,
переделать на фикстуру для генерации рандомного числа, - integer или float с заданным распаределением

2024-06-10 13:40 UTC, denis-perevertov commented
- корректные и некорректные кейсы разделены на разные describe, кейсы генерируются через массивы шаблонов, расписанных на верхнем уровне
- тесты для функций генерируются по шаблонам , из них получается вход: строка для парсера, выход: ожидаемая фикстура
- в фикстуры добавлены типы decimal, array, constant
- циклы for переделаны на test.each

2024-06-16 09:12 UTC, merged